const routes = {
  HOME: "/home",
  BOOK: "/b",
  EDIT: "/edit/:id",
  CATEGORIES: "/categories",
  ADDNEW: "/addnew",
  SEARCH: "/search",
  UPLOADCOVER: "/upload-cover",
  DOWNLOAD: "/download",
  NOTFOUND: "/not-found",
  PDFUPLOADER: "/pdf-uploader",
  SUP: "/s",
  LOGIN: "/login",
  SIGNUP: "/signup",
  AUTH: "/auth",
  DASHBOARD: "/dash",
  H: "/h",
  P: "/p",
  C: "/c",
  N: "/n",
  B: "/b",
  A: "/a",
};
export default routes;
